"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { useRole } from "@/hooks/use-role";
import { useToast } from "@/components/ui/toast";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { TablePagination, usePagination } from "@/components/ui/table-pagination";
import { deleteDeliverableAction } from "@/lib/actions/deliverable";

export interface DeliverableRow {
  id: string;
  reportId: string;
  format: "PDF" | "HTML";
  fileUrl: string | null;
  generatedBy: string | null;
  generatedAt: Date | null;
  reportTitle: string;
  reportIdCustom: string | null;
  generatorUsername: string | null;
}

interface DeliverablesClientProps {
  deliverables: DeliverableRow[];
}

const FORMAT_BADGE: Record<
  string,
  { bg: string; text: string }
> = {
  PDF: {
    bg: "bg-red-100 dark:bg-red-500/20",
    text: "text-red-700 dark:text-red-400",
  },
  HTML: {
    bg: "bg-blue-100 dark:bg-blue-500/20",
    text: "text-blue-700 dark:text-blue-400",
  },
};

function formatDate(date: Date | null) {
  if (!date) return "\u2014";
  return new Date(date).toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default function DeliverablesClient({ deliverables }: DeliverablesClientProps) {
  const [searchQuery, setSearchQuery] = useState("");
  const { isAdmin } = useRole();
  const { addToast } = useToast();
  const router = useRouter();
  const [deleteTarget, setDeleteTarget] = useState<DeliverableRow | null>(null);
  const [deleteLoading, setDeleteLoading] = useState(false);

  async function handleDelete() {
    if (!deleteTarget) return;
    setDeleteLoading(true);

    const result = await deleteDeliverableAction(deleteTarget.id);

    if (result.success) {
      addToast("Deliverable deleted successfully.", "success");
      router.refresh();
    } else {
      addToast(result.error || "Failed to delete deliverable.", "error");
    }

    setDeleteLoading(false);
    setDeleteTarget(null);
  }

  const filteredDeliverables = useMemo(() => {
    const query = searchQuery.toLowerCase().trim();
    if (!query) return deliverables;
    return deliverables.filter(
      (d) =>
        d.reportTitle.toLowerCase().includes(query) ||
        (d.reportIdCustom && d.reportIdCustom.toLowerCase().includes(query))
    );
  }, [deliverables, searchQuery]);

  const { paginatedItems, paginationProps } = usePagination(filteredDeliverables);

  return (
    <>
      {/* Header */}
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-dark dark:text-white">
          Deliverables
        </h2>
        <p className="mt-1 text-sm text-dark-5 dark:text-dark-6">
          Generated report deliverables (PDF / HTML)
        </p>
      </div>

      {/* Search */}
      <div className="mb-4">
        <div className="relative max-w-md">
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search by report title or ID…"
            className="w-full rounded-lg border border-stroke bg-white py-2.5 pl-10 pr-4 text-sm text-dark outline-none transition focus:border-primary dark:border-dark-3 dark:bg-dark-2 dark:text-white dark:focus:border-primary"
          />
          <svg
            className="absolute left-3 top-1/2 -translate-y-1/2 text-dark-5 dark:text-dark-6"
            width="18"
            height="18"
            viewBox="0 0 20 20"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M9.16667 15.8333C12.8486 15.8333 15.8333 12.8486 15.8333 9.16667C15.8333 5.48477 12.8486 2.5 9.16667 2.5C5.48477 2.5 2.5 5.48477 2.5 9.16667C2.5 12.8486 5.48477 15.8333 9.16667 15.8333Z"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
            <path
              d="M17.5 17.5L13.875 13.875"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </div>
      </div>

      {/* Table */}
      <div className="rounded-xl border border-stroke bg-white shadow-1 dark:border-dark-3 dark:bg-gray-dark">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="pl-5">Report ID</TableHead>
              <TableHead>Report Title</TableHead>
              <TableHead>Format</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Generated At</TableHead>
              <TableHead className="pr-5 text-right">Download</TableHead>
              {isAdmin && <TableHead className="pr-5 text-right">Actions</TableHead>}
            </TableRow>
          </TableHeader>
          <TableBody>
            {paginatedItems.length === 0 ? (
              <TableRow>
                <TableCell
                  colSpan={isAdmin ? 7 : 6}
                  className="py-10 text-center text-dark-5 dark:text-dark-6"
                >
                  {deliverables.length === 0
                    ? "No deliverables have been generated yet."
                    : "No deliverables match your search."}
                </TableCell>
              </TableRow>
            ) : (
              paginatedItems.map((d) => {
                const badge = FORMAT_BADGE[d.format] ?? FORMAT_BADGE.PDF;

                return (
                  <TableRow key={d.id}>
                    <TableCell className="pl-5 font-mono text-sm text-dark dark:text-white">
                      {d.reportIdCustom || "\u2014"}
                    </TableCell>
                    <TableCell className="font-medium text-dark dark:text-white">
                      {d.reportTitle}
                    </TableCell>
                    <TableCell>
                      <span
                        className={`inline-block rounded-full px-2.5 py-0.5 text-xs font-medium ${badge.bg} ${badge.text}`}
                      >
                        {d.format}
                      </span>
                    </TableCell>
                    <TableCell className="text-dark-5 dark:text-dark-6">
                      {d.generatorUsername || "\u2014"}
                    </TableCell>
                    <TableCell className="text-dark-5 dark:text-dark-6">
                      {formatDate(d.generatedAt)}
                    </TableCell>
                    <TableCell className="pr-5 text-right">
                      {d.fileUrl ? (
                        <a
                          href={d.fileUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="rounded-md px-3 py-1.5 text-xs font-medium text-primary transition-colors hover:bg-primary/10"
                        >
                          Download
                        </a>
                      ) : (
                        <span className="text-xs text-dark-5 dark:text-dark-6">
                          N/A
                        </span>
                      )}
                    </TableCell>
                    {isAdmin && (
                      <TableCell className="pr-5 text-right">
                        <button
                          type="button"
                          onClick={() => setDeleteTarget(d)}
                          className="rounded-md px-3 py-1.5 text-xs font-medium text-red-500 transition-colors hover:bg-red-500/10"
                        >
                          Delete
                        </button>
                      </TableCell>
                    )}
                  </TableRow>
                );
              })
            )}
          </TableBody>
        </Table>
        {filteredDeliverables.length > 0 && (
          <TablePagination {...paginationProps} />
        )}
      </div>

      {/* Delete Confirmation */}
      <ConfirmDialog
        open={!!deleteTarget}
        title="Delete Deliverable"
        message={`Are you sure you want to delete this ${deleteTarget?.format} deliverable for "${deleteTarget?.reportTitle}"? The file will be permanently removed.`}
        confirmLabel="Delete"
        variant="danger"
        loading={deleteLoading}
        onConfirm={handleDelete}
        onCancel={() => setDeleteTarget(null)}
      />
    </>
  );
}
